version: 1.4.0.{build}
image: Visual Studio 2015
configuration: Release

platform:
- Win32
- x64

environment:
  PFX_ENC_PASS:
    secure: /FOQcwja5XcXpFQqbYnMhOcUTmiwNh4mDFBm9oUh/gaV8Z6V5d45lZrbM8DrKInV
  PFX_PASS:
    secure: MNjAMRrIqjMaFQDSnflh+UHZFZqRwuR9Wmsstd78A1gKnZduxJhiY93rMAnsXMgJ

cache:
  - Explorer++\packages -> Explorer++\**\packages.config

# Decrypt the code signing certificate.
install:
- cmd: >-
    nuget install secure-file -ExcludeVersion

    IF DEFINED PFX_ENC_PASS (secure-file\tools\secure-file -decrypt %APPVEYOR_BUILD_FOLDER%\authenticode.pfx.enc -secret %PFX_ENC_PASS%)

before_build:
- cmd: >-
    nuget restore Explorer++\Explorer++.sln

build:
  project: Explorer++\Explorer++.sln
  verbosity: minimal

# Sign and package the executable.
after_build:
- cmd: >-
    IF DEFINED PFX_PASS ("C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe" sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /f %APPVEYOR_BUILD_FOLDER%\authenticode.pfx /p %PFX_PASS% %APPVEYOR_BUILD_FOLDER%\Explorer++\Explorer++\%PLATFORM%\%CONFIGURATION%\Explorer++.exe)


    cd %APPVEYOR_BUILD_FOLDER%


    IF "%PLATFORM%" == "Win32" (SET "arch=x86") ELSE (SET "arch=x64")


    SET "archiveName=explorer++_%arch%.zip"


    7z a %archiveName% %APPVEYOR_BUILD_FOLDER%\Explorer++\Explorer++\%PLATFORM%\%CONFIGURATION%\Explorer++.exe

    7z a %archiveName% %APPVEYOR_BUILD_FOLDER%\Documentation\User\History.txt

    7z a %archiveName% %APPVEYOR_BUILD_FOLDER%\Documentation\User\License.txt

    7z a %archiveName% %APPVEYOR_BUILD_FOLDER%\Documentation\User\Readme.txt


    7z a explorer++_%arch%_symbols.zip %APPVEYOR_BUILD_FOLDER%\Explorer++\Explorer++\%PLATFORM%\%CONFIGURATION%\Explorer++.pdb


    7z a explorer++_translations.zip %APPVEYOR_BUILD_FOLDER%\Explorer++\Win32\%CONFIGURATION%\Explorer++*.dll
artifacts:
- path: explorer++_x86.zip
- path: explorer++_x86_symbols.zip
- path: explorer++_x64.zip
- path: explorer++_x64_symbols.zip
- path: explorer++_translations.zip